import type { Metadata } from "next";
import { canonical } from "@/lib/seo";

export const metadata: Metadata = {
  ...canonical("/terms-of-service"),
  title: "Terms of Service",
  description:
    "QuicTools terms of service: entertainment-only mockup tools, no valid proof of purchase, prohibited misuse including reimbursement or refund fraud, and client-side utility tools.",
};

export default function TermsOfServicePage() {
  return (
    <div className="mx-auto w-full max-w-3xl px-4 py-10">
      <h1 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-gray-500">
        Last updated:{" "}
        {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
      </p>

      <div className="mt-6 space-y-6 text-[15px] leading-relaxed text-gray-600">
        <section>
          <h2 className="mb-2 text-lg font-semibold text-gray-900">Acceptance of terms</h2>
          <p>
            By accessing or using QuicTools, you agree to be bound by these
            Terms of Service. If you do not agree with any part of these terms,
            you should not use the site.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-gray-900">
            Entertainment-only mockup tools
          </h2>
          <p>
            Our mockup and generator tools — including the fake caller ID,
            fake receipt, fake chat, fake tweet, and fake notification
            generators — are created{" "}
            <strong>strictly for entertainment, demonstration, and novelty
            purposes only</strong>. Images generated by these tools are not
            authentic communications, and they are not intended to deceive,
            impersonate, misrepresent, or defraud any person or organization.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-gray-900">
            Receipts are not valid proof of purchase
          </h2>
          <p>
            Receipts generated with the receipt generator are{" "}
            <strong>not valid receipts</strong> and are not proof of purchase.
            They must not be used as evidence of a transaction, for expense
            reimbursement, for tax filing, for warranty or return/refund
            claims, or for any other financial or legal purpose. Failing to
            comply may constitute reimbursement fraud or refund fraud, which
            are serious offenses.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-gray-900">
            Caller ID is simulated
          </h2>
          <p>
            Caller ID images are simulated and do not represent real phone
            calls, carriers, or telephone service providers. They are for
            entertainment only and must not be used to misrepresent, prank,
            harass, or impersonate others.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-gray-900">
            Prohibited uses
          </h2>
          <p>You agree not to use QuicTools to:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Create content that is illegal, fraudulent, deceptive, or misleading.</li>
            <li>Impersonate any person, business, brand, or government entity.</li>
            <li>
              Generate documents used to defraud, including fake receipts for
              reimbursement, refund, or return fraud.
            </li>
            <li>
              Infringe the intellectual property rights of others, including
              uploading or generating copyrighted content you do not own.
            </li>
            <li>
              Harass, threaten, or invade the privacy of others.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-gray-900">
            Client-side utility tools
          </h2>
          <p>
            Utility tools — such as invoice, resume, signature, countdown,
            name picker, text-to-handwriting, and meme generators — run
            entirely in your browser. Any data you enter stays on your device.
            We do not store or transmit the content you create.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-gray-900">
            No warranties
          </h2>
          <p>
            The tools are provided &ldquo;as is&rdquo; without warranties of any
            kind, express or implied. While we aim for accuracy, we make no
            guarantee that any output is error-free or fit for a particular
            purpose. You are solely responsible for how you use the content you
            generate.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-gray-900">
            Limitation of liability
          </h2>
          <p>
            To the fullest extent permitted by law, QuicTools shall not be
            liable for any direct, indirect, incidental, consequential, or
            special damages arising from your use of the site or reliance on
            any generated content.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-gray-900">Changes</h2>
          <p>
            We may update these Terms of Service from time to time. Continued
            use of the site after changes are posted constitutes acceptance of
            the revised terms.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-gray-900">Contact</h2>
          <p>
            Questions about these terms? Contact us at{" "}
            <a href="mailto:quictools.cc@gmail.com" className="font-medium text-accent-600 hover:underline">
              quictools.cc@gmail.com
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}